### ISSUE TITLE
Client-side Dependency

### ISSUE THREAD

**Issue by Inflectus** [Dremoline/LongerLoginTimes#4]
Hi,

I'm having an issue running this on my Vault Hunters server. While the mod itself installs correctly, and is technically server-sided only, the library it depends on needs to be installed client-side, so some installation on the client is required anyway.

Is it possible to upload a separate branch of the mod for the various versions that doesn't depend on the library? While someone like me wouldn't mind automatically installing the library to my client, it makes it discouraging and difficult for players with less patience or understanding of modded Minecraft, even through CurseForge.

**Comment by SmallSansSerif** [comment]
Can you remove the dependency on this mod so it can be run server side only? The dependency library needs both client and server.

**Comment by Dremoline** [comment]
Hey, this is part of the config library of Supermartijn642. Please feel free to contact him about this issue.
